### ISSUE TITLE
choco uninstall says 'successfully uninstalled gauge' even when the uninstallation has failed

### ISSUE THREAD

**Issue by sswaroopgupta** [getgauge/chocolatey-packages#2]
**Expected behavior**
choco uninstall should give uninstall fail message when failed

**Actual behavior**
choco uninstall says 'successfully uninstalled gauge' even when the uninstallation has failed

**Steps to reproduce**
1. Run the cmd line - do not use the admin permission
2. choco uninstall gauge

```
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider setting
 'allowGlobalConfirmation'. Run 'choco feature -h' for more details.
Do you want to run the script?
 1) yes
 2) no
 3) print
yes
 Skipping auto uninstaller - AutoUninstaller feature is not enabled.
This is try 1/3. Retrying after 300 milliseconds.
 Error converted to warning:
 Access to the path 'gauge.nupkg' is denied.
This is try 2/3. Retrying after 400 milliseconds.
 Error converted to warning:
 Access to the path 'gauge.nupkg' is denied.
Maximum tries of 3 reached. Throwing error.
Attempted to remove 'C:\ProgramData\chocolatey\lib-bkp\gauge' but had an e

 Access to the path 'gauge.nupkg' is denied.
 gauge has been successfully uninstalled.

Chocolatey uninstalled 1/1 packages. 0 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

**Comment by apoorvam** [comment]
This issue is not reproducible as per Chocolatey v0.10.3 and Gauge v0.7.0.

**Comment by sriv** [comment]
@sguptatw - is this still an issue?

**Comment by sswaroopgupta** [comment]
Unable to test this as the uninstallation has a different issue

<img width="676" alt="uninstall_with_choco" src="https://cloud.githubusercontent.com/assets/6310197/23501536/40981b9c-ff5a-11e6-8ab2-ae7069f470d5.png">

**Comment by sriv** [comment]
Fixed via 01c6fbc. Fix should be available in nightly >= 09/03/2017

**Comment by sswaroopgupta** [comment]
Getting the same issue. Not sure if this is because choco considers only the released versions of Gauge.

**Comment by sriv** [comment]
Choco package has not been published. See [this](https://github.com/getgauge/chocolatey-packages/issues/4#issuecomment-286030236).
