### ISSUE TITLE
Installation failure on Windows 10

### ISSUE THREAD

**Issue by bfaloona** [getgauge/chocolatey-packages#3]
Installation failed using choco and an elevated cmd prompt.

Env: Windows 10 Enterprise, 64bit

Installation via the zip installer appears to have succeeded.

    C:\WINDOWS\system32>choco install guage
    Chocolatey v0.10.3
    [Pending] Removing incomplete install for 'easy.install'
    [Pending] Removing incomplete install for 'python3'
    Installing the following packages:
    guage
    By installing you accept licenses for the packages.
    guage not installed. The package was not found with the source(s) listed.
     If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
     Version: ""
     Source(s): "https://chocolatey.org/api/v2/"

    Chocolatey installed 0/1 packages. 1 packages failed.
     See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

    Failures
     - guage - guage not installed. The package was not found with the source(s) listed.
     If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
     Version: ""
     Source(s): "https://chocolatey.org/api/v2/"

**Comment by bfaloona** [comment]
Attached chocolatey.log

[gauge-chocolatey.log.txt](https://github.com/getgauge/chocolatey-packages/files/784393/gauge-chocolatey.log.txt)

**Comment by sriv** [comment]
The package name you've specified is incorrect. The logs indicate you are attempting to install `guage`. It should be `gauge`. Can you please try `choco install gauge`?
