### ISSUE TITLE
allow plugins to be installed via choco install

### ISSUE THREAD

**Issue by sriv** [getgauge/chocolatey-packages#4]
Add support to pass option to take plugins to be installed, and pass them to the installer.

Depends on getgauge/gauge#587

**Comment by sriv** [comment]
works, pass `--install-arguments="/PLUGINS ruby,csharp"`. This doesn't have nightly builds.

**Comment by sswaroopgupta** [comment]
how can I test this before it is released? Choco takes the released Gauge exe.

**Comment by sriv** [comment]
there are two components here:

- choco package script
- gauge installer.

You can check the choco package by running a local install (ref [here](http://stackoverflow.com/a/26053111/326543)

But the problem is that the chocolatey script pulls from github releases (https://github.com/getgauge/gauge/releases), so this can't be tested unless the urls are made configurable.

**Comment by sswaroopgupta** [comment]
I am not able to uninstall #622

**Comment by sswaroopgupta** [comment]
Working as expected.
